const actions = {
    CHANGE_ACTIVE_LINE_START_END_POS: 'CHANGE_ACTIVE_LINE_START_END_POS',
    CHANGE_DIRECTION: 'CHANGE_DIRECTION',
    CHANGE_ACTIVE_LINE: 'CHANGE_ACTIVE_LINE',
    FILL_LINE: 'FILL_LINE',
    CHANGE_GAME_STATUS: 'CHANGE_GAME_STATUS'
}

export { actions as ACTIONS };